# Generated by Django 2.2 on 2019-04-09 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='title',
            new_name='a',
        ),
        migrations.RemoveField(
            model_name='member',
            name='body',
        ),
        migrations.RemoveField(
            model_name='member',
            name='create_date',
        ),
        migrations.AddField(
            model_name='member',
            name='b',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='c',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
